name: frontend deploy

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest 

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          script: | # 실행할 스크립트
            rm -rf remind-map-frontend
            echo "삭제 완료"
            git clone --branch prod https://github.com/Goorm-Hongsam/remind-map-frontend.git
            docker-compose down
            docker rmi -f $(docker images -q)
            docker builder prune -a --force
            docker-compose up -d
            
